i1661: Allow unidirectional backup targets
vimc/bb8 pull request #17
Opened 2018-04-19 11:12 UTC by MartinEden

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1661

2018-04-19 11:19 UTC, richfitz requested changes
I can't run this without upgrading my python because of the f-string version.  Can we (not necessarily here) think about how to start testing this in general?  This all looks eminently testable...

2018-04-19 11:19 UTC, richfitz commented on bin/backup.py
> +            logging.info(f"  (Skipping backing up {target.id} - backup is "
f-format strings require python3.6 which is really recent (recent enough that production does not have it for example).  They're nice but possibly not _that_ nice (there is this back though: https://github.com/asottile/future-fstrings).

2018-04-19 12:40 UTC, hillalex reviewed
Should there be a corresponding PR in `montagu-bb8`, that updates the `config.json` we use?

2018-04-19 12:41 UTC, littledice commented on bin/targets.py
> +        self.restore = data.get("restore", True)
So by default both are set to true. Ok.

2018-04-19 12:44 UTC, hillalex approved these changes
I see that this just sets everything to both backup and restore by default, which seems ok. The update to `montagu-bb8` config can happen in https://vimc.myjetbrains.com/youtrack/issue/VIMC-1663

2018-04-20 10:13 UTC, MartinEden commented on bin/backup.py
> +            logging.info(f"  (Skipping backing up {target.id} - backup is "
I hadn't realized they were so new. That's a shame, they are nice. I've removed them.

2018-04-20 10:14 UTC, MartinEden commented
@littledice: The update to config in montagu-bb8 is the other PR in the the ticket: https://github.com/vimc/montagu-bb8/pull/2

@richfitz: Agreed about tests. I've added this must have ticket to the sprint and will work on it early next week: https://vimc.myjetbrains.com/youtrack/issue/VIMC-1687

2018-04-20 14:22 UTC, richfitz approved these changes

2018-04-20 14:30 UTC, merged