i1690: Add log viewing capabilities, and log each run to separate file
vimc/bb8 pull request #21
Opened 2018-04-20 13:17 UTC by MartinEden

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1690

With this change you can run `bb8 log` to view the most recent log, no muss, no fuss. There are also options to list available log files, and to view a particular one.

Rich, I decided I was overthinking this: If you want to use `less`, you can just run `bb8 log | less`. This might take a few seconds if its a big log file while the whole thing travels via the pipe, as opposed to less reading as it needs to, but I think that's acceptable.

2018-04-23 07:47 UTC, richfitz reviewed
This looks good to me but I have not run it - is there a simple way of testing things (e.g., running this against the  bb8 installations that are running at the moment?)

2018-04-25 13:12 UTC, MartinEden commented
I just tested it locally. Easy enough:

```
sudo ./setup ../config.json orderly
bb8 restore # Repeat this to get more logs
bb8 log --list
etc.
```

2018-04-25 14:28 UTC, hillalex approved these changes

2018-04-26 11:25 UTC, richfitz requested changes
Minor changes here, but confirmed working and nice to use! I suspect that a fully subcommanded approach would be best - I think we're going to end up eventually wanting something like `bb8 log grep <pattern>` and that would allow that unambiguously

2018-04-26 11:25 UTC, richfitz commented on bin/main.py
> +  main.py log [--version=<version>]
Would this second form would be more idiomatic as `main.py log [<version>]`?

2018-04-26 11:25 UTC, richfitz commented on bin/main.py
> +  main.py log [--version=<version>]
Or even as `main.py log list` or `main.py log show [<version>]` as the two forms

2018-04-26 11:25 UTC, richfitz commented on bin/main.py
> +  main.py log [--version=<version>]
Also, the name `main.py` should probably be bb8 so that running `bb8 --help` gives more understandable output

2018-04-26 12:24 UTC, MartinEden commented on bin/main.py
> +  main.py log [--version=<version>]
How's this?

2018-04-26 13:10 UTC, richfitz commented on bin/main.py
> +  main.py log [--version=<version>]
nice!

2018-04-26 13:10 UTC, richfitz approved these changes

2018-04-26 13:11 UTC, merged