i1687: Run bb8 tests through TeamCity
vimc/bb8 pull request #22
Opened 2018-04-25 14:54 UTC by MartinEden

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1687

This doesn't add any new tests. It just gets the tests running through TeamCity on every commit. I say "just", but it's taken me several hours!

Python has gone through several unit testing frameworks in the last few years. Part of the effort has been researching which one to use (looks like `pytest`) and then upgrading things to work with that.

2018-04-25 14:55 UTC, MartinEden commented on bin/requirements.txt
> -python-crontab==2.2.8
Noticed we didn't need this any more

2018-04-25 14:56 UTC, MartinEden commented on testing/test-setup.sh
> -       /src/setup
For now I have just removed this script which tested setting up bb8 on a new machine, as it was out of date, from well before we dockerised bb8. I may write a replacement for this in the future, or I may confine myself to unit tests.

2018-04-25 19:03 UTC, hillalex approved these changes

2018-04-26 08:17 UTC, richfitz requested changes
Nice :)

Is it worth setting up with https://github.com/JetBrains/teamcity-messages so that we get easier-to-use test failures too?

2018-04-26 09:32 UTC, MartinEden commented
@richfitz Already done, I thought. See `requirements-dev.txt` and the entrypoint of the tests `Dockerfile`.

2018-04-26 11:13 UTC, richfitz commented
Sorry - you're right - I must have picked up the wrong build

2018-04-26 11:13 UTC, richfitz approved these changes

2018-04-26 11:34 UTC, merged